server:
  port: 9296
  
spring:
  application:
    name: CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aritraibm/ms-cloud-config 
          clone-on-start: true
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: 
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
   
